#! /usr/bin/Rscript

# set working directory as T2CD

# simulations to test accuracy of estimating growth regime
# regime 1 generated by gp or poly

library(parallel)
source('./helperfunction/helperfn.R')
source('./method/bsWLS.R')

### setup

args = commandArgs(trailingOnly = TRUE) 
# poly or gp

simnum = 100

d_list = seq(-0.45, 1.45, by = 0.2)
tau_list = seq(15, 45, by = 5)
taupercent_list = tau_list/70
truetau_list = tau_list

# Calculate the number of cores
no_cores = detectCores() - 1
# Initiate cluster
outfilename = paste('./Simulations/Univariate/growthsim_', args[1], '.txt', sep = '')
cl = makeCluster(no_cores, type = 'FORK', outfile = outfilename)
# each iteration of function output as a list entry
# each function output is a named list

fit1_k = function(k){
  tauN = length(truetau_list)
  dN = length(d_list)
  
  rmse.full = rmse.part = rmse.diff = 
    valscoeff.diff = resdcoeff.diff = valslambda.diff = resdlambda.diff = 
    matrix(NA, dN, tauN, dimnames = list(d_list, truetau_list))
  
  for (i in 1:dN){
    for (j in 1:tauN){
      sim_ij = sim.simple(tau.percent=taupercent_list[j], d=d_list[i], 
                          phip=0, piq=0,
                          hetero1=TRUE, regime1=args[1],
                          seed=k)
      
      tim = sim_ij$tim
      seg_reg1 = scale(sim_ij$gt1, center = F) # ground truth growth trend
      res_mean = c(sim_ij$res)/attributes(seg_reg1)$`scaled:scale`
      n1 = length(seg_reg1) # length of regime 1
      
      fit1.full = refitWLS(tim, res_mean)
      fit1.part = refitWLS(tim[1:n1], res_mean[1:n1])
      
      rmse.full[i,j] = sqrt(mean((seg_reg1 - fit1.full$fit.vals[1:n1])^2))
      rmse.part[i,j] = sqrt(mean((seg_reg1 - fit1.part$fit.vals)^2))
      # comparison between full and part fit
      rmse.diff[i,j] = sqrt(mean((fit1.full$fit.vals[1:n1] - fit1.part$fit.vals)^2))
      nk.part = fit1.part$model.vals$fit$nk
      valscoeff.diff[i,j] = mean(abs(fit1.full$model.vals$fit$coef[1:nk.part] - fit1.part$model.vals$fit$coef))
      resdcoeff.diff[i,j] = mean(abs(fit1.full$model.resd$fit$coef[1:nk.part] - fit1.part$model.resd$fit$coef))
      valslambda.diff[i,j] = abs(fit1.full$model.vals$lambda - fit1.part$model.vals$lambda)
      resdlambda.diff[i,j] = abs(fit1.full$model.resd$lambda - fit1.part$model.resd$lambda)
    }
  }
  return(list(rmse.full = rmse.full, rmse.part = rmse.part, rmse.diff = rmse.diff,
              valscoeff.diff = valscoeff.diff, resdcoeff.diff = resdcoeff.diff,
              valslambda.diff = valslambda.diff, resdlambda.diff = resdlambda.diff))
}

fit1 = parLapply(cl, 1:simnum, fit1_k)

save.image(paste('./Simulations/Univariate/simulate_growth_', args[1],'.RData',
                 sep = ''))
stopCluster(cl)
