#! /usr/bin/Rscript

# set working directory as T2CD

# simulations to test accuracy of estimating d and tau, include computation time
# regime 1 generated by gp

library(parallel)
source('./helperfunction/helperfn.R')
source('./helperfunction/competingmethods.R')
source('./method/t2cd_step.R')
source('./method/t2cd_sigmoid.R')

### setup

args = commandArgs(trailingOnly = TRUE) 
# TRUE/FALSE for hetero1 (heteroscedastic noise for regime 1) in sim.simple()
# phip and piq for ARFIMA model
if (length(args) > 0){
  hetero1 = args[1]
  phip = as.numeric(args[2])
  piq = as.numeric(args[3])
}else{
  hetero1 = TRUE
  phip = piq = 0
}

simnum = 100

d_list = seq(-0.45, 1.45, by = 0.2)
tau_list = seq(15, 45, by = 5)
taupercent_list = tau_list/70
truetau_list = tau_list

# Calculate the number of cores
no_cores = detectCores() - 1
# Initiate cluster
outfilename = paste('./Simulations/Univariate/gpsim', phip, piq, '.txt', sep = '')
cl = makeCluster(no_cores, type = 'FORK', outfile = outfilename)
# each iteration of function output as a list entry
# each function output is a named list

cpt_k = function(k){
  print(k)
  tauN = length(truetau_list)
  dN = length(d_list)
  
  tau_step = d_step = ptime_step =
    tau_sigmoid = d_sigmoid = ptime_sigmoid = 
    tau_ecp = d_ecp = ptime_ecp = 
    tau_ecp.diff = d_ecp.diff = ptime_ecp.diff = 
    d_seg = ptime_seg = 
    d_truetau = ptime_truetau = 
    matrix(NA, dN, tauN, dimnames = list(d_list, truetau_list))
  
  for (i in 1:dN){
    for (j in 1:tauN){
      sim_ij = sim.simple(tau.percent=taupercent_list[j], d=d_list[i], phip=phip, piq=piq,
                          hetero1=hetero1, regime1='gp', seed=k)
      
      # T2CD-step
      s = proc.time()
      res_step = t2cd_step(sim_ij, t.max = 70, use_arf = F)
      ptime = proc.time() - s
      tau_step[i,j] = res_step$tau
      d_step[i,j] = res_step$d
      ptime_step[i,j] = ptime[1]

      # T2CD-sigmoid
      s = proc.time()
      res_sigmoid = t2cd_sigmoid(list(res=matrix(sim_ij$res,1), tim=matrix(sim_ij$tim,1)), t.max = 70)
      ptime = proc.time() - s
      tau_sigmoid[i,j] = res_sigmoid$tau
      d_sigmoid[i,j] = res_sigmoid$d
      ptime_sigmoid[i,j] = ptime[1]
      
      # ecp, original
      s = proc.time()
      res_ecp = ecp_d(list(res=matrix(sim_ij$res,1), tim=matrix(sim_ij$tim,1)), dflag = 'original')
      ptime = proc.time() - s
      tau_ecp[i,j] = res_ecp$tau
      d_ecp[i,j] = res_ecp$d
      ptime_ecp[i,j] = ptime[1]
      
      # ecp, diff
      s = proc.time()
      res_ecp.diff = ecp_d(list(res=matrix(sim_ij$res,1), tim=matrix(sim_ij$tim,1)), dflag = 'diff')
      ptime = proc.time() - s
      tau_ecp.diff[i,j] = res_ecp.diff$tau
      d_ecp.diff[i,j] = res_ecp.diff$d
      ptime_ecp.diff[i,j] = ptime[1]
      
      # segmented at fixed tau
      s = proc.time()
      res_seg = estd(list(res=matrix(sim_ij$res,1), tim=matrix(sim_ij$tim,1)), tau = 50)
      ptime = proc.time() - s
      d_seg[i,j] = res_seg$d
      ptime_seg[i,j] = ptime[1]
      
      # segmented with true tau
      s = proc.time()
      res_truetau = estd(list(res=matrix(sim_ij$res,1), tim=matrix(sim_ij$tim,1)), tau = truetau_list[j])
      ptime = proc.time() - s
      d_truetau[i,j] = res_truetau$d
      ptime_truetau[i,j] = ptime[1]
    }
  }
  return(list(tau_step = tau_step, d_step = d_step, ptime_step = ptime_step,
              tau_sigmoid = tau_sigmoid, d_sigmoid = d_sigmoid, ptime_sigmoid = ptime_sigmoid,
              tau_ecp = tau_ecp, d_ecp = d_ecp, ptime_ecp = ptime_ecp,
              tau_ecp.diff = tau_ecp.diff, d_ecp.diff = d_ecp.diff, ptime_ecp.diff = ptime_ecp.diff,
              d_seg = d_seg, ptime_seg = ptime_seg,
              d_truetau = d_truetau, ptime_truetau = ptime_truetau))
}

cptresults = parLapply(cl, 1:simnum, cpt_k)

save.image(paste('./Simulations/Univariate/simulate_gp', hetero1, phip, piq,'.RData',
                 sep = ''))
stopCluster(cl)
